[[Xorg_xcb_util_image]]
arch = "armv7l"
git-tree-sha1 = "47a8f4576f6ecc853dce1379da8d33d59d4dc9bb"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "1cceb186b5c59e4782b6c9f4ff85706ddb42dc00f1bfba34795cea0ea0d3c9c5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.arm-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "912f29c55cc736110f9908832724a93af78ccfec"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "e3517d0be3bd6a40658a6cc0ac6967323934268704515ff3b72850c15a4ac033"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "aarch64"
git-tree-sha1 = "a59ee7f4d138bd1839a080d3f51ec16cc5baac5b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "339ed18921b760913c9d3b5360429541b8e6aa3f18a6cd93666e45ea99a98ac7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "i686"
git-tree-sha1 = "3efc1943a9e4073822aaede84b135ad130a6ef9f"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "07d79d1e5bec7c5508cc9770bec386b107695313f31c2c15af0c4eaf4fa9b236"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "aarch64"
git-tree-sha1 = "8ced1eba129aacaeca1fe9198fdd6c9fbe2347ab"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "24ea2948d0221db5aace38cf10dfc43efdd61c422c937c6f2be22d9c7c8bd6bb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "7553520499cade45ecb07d86f7e438a941851e4f"
os = "freebsd"

    [[Xorg_xcb_util_image.download]]
    sha256 = "68852a0747fad774d908542b59af1ee89c07b40a184cf8272690051d6b2d584a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xcb_util_image]]
arch = "powerpc64le"
git-tree-sha1 = "1315cdc745005e8f6e61deb95886de532f267120"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "72c6b7dd3ac9728bbea428281725eaa0b3cd1bd023196ed265164b3d5718b83d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "i686"
git-tree-sha1 = "e88b1e9eaa5055530f76df52de9c1e8bb41543ef"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "e939138f2f8310ed41282e4c59d49f3da3272621d7e29685cd75d9cc6f4de539"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "16f72344c33db7731ee821db6252d889797817d2"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "52b133626bf30a09cde0363f49b8fc3affd58b4c0fefcae9c817e4f71c9f408f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "armv7l"
git-tree-sha1 = "8142c069eea1c92d34c4c627fb0751301371f29f"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "1c4742498e1c5f6992312df72110daed999d279f3e958900d537540b63f68c4c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+0/Xorg_xcb_util_image.v0.4.0.arm-linux-musleabihf.tar.gz"
